=head1 NAME

xl.snapshot.cfg - XL Domain Snapshot Configuration File Syntax

=head1 DESCRIPTION

without snapshot configuration file, xl snapshot-create could create internal
domain snapshot or internal disk snapshot. To create a user-defined domain
snapshot, xl requires a domain snapshot config file. Typically these live in
`/var/lib/xen/snapshots/UUID/snapshotdata-d.NAME.libxl-json` where
UUID is the uuid of domain and the NAME is name of snapshot.
it is highly recommend that the external file snapshot should locate the same
directory with snapshot configuration file and memory save image.
here is two examples for internal domain snapshot and external domain snapshot:
"/etc/xen/examples/xlsnapshot.internal", "/etx/xen/examples/xlsnapshot.external".

=head1 SYNTAX

A domain config file consists of a series of C<KEY=VALUE> pairs. it share the
same rules with xl.cfg

=head1 OPTIONS

=over 4

=item B<name="NAME">

Specifies the name of the domain snapshot. Names of snapshots existing on a
single domain must be unique. if ignored, it will be the epoch second from 1,
Jan 1970.

=item B<description="DESCRIPTION">

the snapshot description.

=item B<creationtime="CREATIONTIME">

the creation time of this snapshot, it will be the epoch second from 1, Jan
1970. this field could not be specified by user. it will be ignored in domain
snapshot creation.

=item B<memory="PATHNAME">

describe the location of memory save image, this image is as same as the image
in "xl save". the value could be the full directory of the location of memory
save image or "yes" which means `/var/lib/xen/snapshots/UUID/NAME.save`.
if ignored, this snapshot will be a disk only snapshot.

=item B<disk=[ "DISK_SPEC_STRING", "DISK_SPEC_STRING", ...]>

the disk snapshot description. See F<docs/misc/xl-disk-configuration.txt> for
full description. for internal snapshot, user should provide vdev and
target=null. for external snapshot, user should provide vdev, format, target.
format is the format of external snapshot file. only qcow2 is allowed. target
is the external snapshot file including full path.

=back

